version: '2'
services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
      - 3306:3306      
    environment:
      - "MYSQL_ROOT_PASSWORD=Admin888"
    mem_limit: 1g # memory limit
    restart: always

  accountingapp:
    container_name: accountingapp
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
      - 10230:80
    links:
      - mysql:mysql-server
    depends_on:
      - mysql
    environment:
      ConnnectionStrings__AccountingConnection: server=mysql-server;database=test;uid=root;pwd=Admin888