version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306      
    environment:

  accountingapp:
    container_name: accountingapp
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
      - 10230:80
    links:
      - mysql:mysql-server
    depends_on: 
      - mysql
