FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR app

# copy everything and build
COPY . .
RUN dotnet restore && dotnet publish -c Release -o out

# build runtime image
FROM microsoft/aspnetcore:2.0
WORKDIR app
COPY --from=build-env /app/AccountingApp/out .
EXPOSE 80
ENTRYPOINT ["dotnet", "AccountingApp.dll"]
