apiVersion: v1
kind: Service
metadata:
  name: accountingapp-service
spec:
  selector:
    app: accountingapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31254
  type: NodePort